
### VE AS CARONAS:
GET  http://localhost:3333/carona
Content-Type: application/json

### CRIA CARONA:
POST   http://localhost:3333/carona
Content-Type: application/json

{"nome": "Chaina", "nota": 5.0, "localSaida": "UFES-VIX", "localChegada": "Alegre-ES"," data": "24/10/2020", "valor": 50.00, " horaSaida": "14h","horaChegada": "17:30", "embarque": "creio que esse campo seja desnecessário", "imagem": "uns carro massa", "desembarque": "também desnecessário os caras que se resolvam", "vagas": "4", "userEmail": "lucas@gmail.com", "telefone": "9999-9999", "interesse": "", "votos":"1"     }

###DELETA:
DELETE    http://localhost:3333/carona/delete
Content-Type: application/json

{"_id": "5ec45b9a91a38e19b8c9c21f" }

### VE SE TEM VAGA:

POST  http://localhost:3333/carona/vagas
Content-Type: application/json


{"_id": "5ec45b7f91a38e19b8c9c21e"}

### VOTANA CARONA:
POST      http://localhost:3333/carona/votar
Content-Type: application/json


{"_id": "5ec45b7f91a38e19b8c9c21e", "nota": 1}

### INTERESSE
POST      http://localhost:3333/carona/interesse
Content-Type: application/json


{"_id": "5ec57f3ee6eea622f4eafa52", "novoInteresse":"5ec019325f3fb10017240d3f" }

###
PUT       http://localhost:3333/carona/retornaInteresse
Content-Type: application/json


{"_id": "5ec567d08ddcaf0017cd0eb8" }
